### ISSUE TITLE
Augment Exp class with deduceInNumberSet method

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#104]
As exemplified in the Add class (found in number/addition/add.py), add a deduceInNumberSet method to  the exponentiation Exp class (found in number/exponentiation/exp.py) which will then augment the automation related to Exp closure deductions. This also then would benefit from augmenting the current number/exponentiation context theorems with a number of related closure theorems, most of which can be found in the old _theorems_old.ipynb in that same context. This process would then allow more automatic closure conclusions such as deducing that 2^t is a positive natural when t a positive natural, etc. This is related to Issue #97 , arising as we flesh out various classes and related theorems to more easily establish theorems used in the quantum phase estimation algorithm.
Seems reasonable to create a separate branch for this issue with the hope that it can fairly quickly be merged into master (rather than incorporating the modifications in the recently-established 97-Update-QPE-content branch).

**Comment by wdcraft01** [comment]
I believe the modifications to address this issue are now ready for review and potential pull request. Here is a summary of what has been done:

(1) Established the new branch 104-Augment-Exp-class–… off the then-current master. 

(2) Transferred and updated the theorems from the old exponentiation/_theorems_old.py into the current exponentiation._theorems_.ipynb, which included a number of closure theorems for exponential operations and sqrt operations, as well as a number of more general exponential operations theorems. 

(3) Fixed a small attribute-assignment bug in the number/modula/Abs class. 

(4) Implemented a deduceInNumberSet() method for the Exp class, which utilizes many of the newly refurbished  closure theorems found in the exponentiation context. 

(5) Implemented a deduceInNumberSet() method for the Sqrt class, utilizing the newly refurbished closure theorems. 

(6) Eliminated several of the more redundant-seeming exponentiation theorems (where theorems about equalities were included in both directions). 

(7) Fixed a notational/fencing bug in the Exp class that was popping up when applying an exponent to a product.  

(8) Established a more general closure theorem for exponentials that combines two others, but this is not included in the deduceInNumberSet() method process because there seems to be an issue with dealing efectively with an Or() constraint in the theorem conditions. Opened a separate Issue #105 on this issue. 

(9) Limited testing of the closure theorems suggests all is working well, EXCEPT for something odd happening in the RealsPos closure theorem for sqrt, where the system seems to be having a problem (infinite loop or something?) proving 2 is a positive natural (despite it being able to use that fact for the complex-related closure theorem). 

(10) Established the RealNonNegSet number set and related theorems and definitions. 

(11) Transferred and updated inRealsNeg_iff_negative and inRealsPos_iff_positive thms from the old sets/real/theorems.py to the sets/real/_theorems_.ipynb to allow the deduceMemberUpperBound() and deduceMemberLowerBound() methods to work in sets/real/real.py.

**Comment by wwitzel** [comment]
I'd like to see a demonstration of the infinite loop referred to in #9 above.

**Comment by wdcraft01** [comment]
Further modifications now ready for review and potential pull request. Picking up from the earlier list posted above, here is a summary of what has been done:

(12) Submitted pull request evening of Sun 2/23/2020. 

(13) Eliminated the Sqrt class, substituting for it a sqrt() fxn instead that uses the Exp class with a special styles key word 'radical' set to 'sqrt,' which then affects the output style to use a sqrt radical (this was intended to be generalizable to other radicals such as cube roots or nth roots). 

(14) Established a natPosInRealsPos thm in the number/sets/reals context and added the thm to the list of thms being imported at the end of number/sets/reals/real.py, all of which then facilitated the automation in proving something like 2 is in positive nats (which was earlier causing some sort of endless loop or other eventual freeze — see item (9) above). 

(15) Established a minimal deduceInNumberSet() method in the Div class and refreshed an accompanying divRealClosure theorem in the number/division context. 

(16) Modified the Mult.exponentCombination() method to work with the new sqrt() fxn (replacing the Sqrt class), and along the way constructed a temporary fix in the form of a crude InSet. extractInitArgValue() method that takes the domain operand_or_operands of the form [a, b, set_name] and returns just the first element as the desired element and the last element as the domain, which allows the exponentCombination() method to proceed, and I'm hoping doesn't interfere with other InSet-involving processes (various tests suggests this is working fine).

(17) python build.py with --clean, --justessential, --justdemos, and --justproofs all run completely with no troubles reported, and my GitHub desktop app reports that “This branch is up to date with master.”

**Comment by wwitzel** [comment]
This was pulled into master from 104-Augment-Exp-class-with-deduceInNumberSet-method.
