### ISSUE TITLE
Logical OR condition in theorem not evaluated

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#105]
Sometimes it is useful to express a theorem such that the condition(s) placed on the variable(s) involve slightly complicated booleans. For example in the linked image below are shown three closure theorems for the number/exponentiation context. The first two express closure conditions for two different but related situations, and the third theorem attempts to combine them into a single theorem using an And nested within an Or:
![image](https://user-images.githubusercontent.com/41027033/75119325-23192400-563f-11ea-9c5c-1ec6f1010b4b.png)
The first two theorems work fine and have been incorporated into the details of the Exp method deduceInNumberSet(). The third, comprehensive theorem runs into trouble when trying to specialize. Logically, the specialization assumptions for that 3rd thm should allow either side of the Or conditions to be specified. Specialization appears to work when we supply the LHS of the constraint. For example:
`expRealClosure.specialize({a:x, b:y}, assumptions=[InSet(x, Reals), InSet(y, Reals), Greater(x, zero)])`
produces:
![image](https://user-images.githubusercontent.com/41027033/75119579-607eb100-5641-11ea-8ff7-7395b2049db1.png)
but trying to specialize using the RHS of the OR constraint, like this:

> expRealClosure.specialize({a:x, b:y}, assumptions=[InSet(x, Reals), InSet(y, Reals), GreaterEq(x, zero), NotEquals(y, zero)])

or like this:

> expRealClosure.specialize({a:x, b:y}, assumptions=[InSet(x, Reals), InSet(y, Reals), And(GreaterEq(x, zero), NotEquals(y, zero))])

produces an error message:

> ProofFailure: Unable to prove (x > 0) or ((x >= 0) and (y != 0)) assuming {x in Reals, y in Reals, x >= 0, y != 0}: Failure to automatically 'conclude'
> SpecializationFailure: Proof step failed assuming {x in Reals, y in Reals, x >= 0, y != 0}: Unmet specialization requirement: (x > 0) or ((x >= 0) and (y != 0)) when specializing |- forall_{a, b in Reals | (a > 0) or ((a >= 0) and (b != 0))} (a^{b} in Reals) with {a: x, b: y}

as if the system isn't able to conclude the OR condition is true from the RHS of the Or being true. I've tried a variety of notational variations in calling the specialization method, all with the same result.

**Comment by wwitzel** [comment]
This is an interesting failure of the automation of logical OR and AND.  It is curious that it handles it fine when the left or the OR is assumed but not the right of the OR.  I'd like to see what the proof looks like of the former.

**Comment by wdcraft01** [comment]
Hah. So I looked more carefully at this and here is an example result:
![image](https://user-images.githubusercontent.com/41027033/75177957-5d90c880-56f4-11ea-8ad0-b02ed0ace5ad.png)
As you can see, what happened in that specific example attempt, despite my attempt to specialize the general `expRealClosure` theorem with the `Greater(x, zero)` assumption, the proof has *actually* used the specialized `expRealClosureBasePos` theorem instead, bypassing my intended `expRealClosure` theorem. It turns out that the `expRealClosureBasePos` theorem was invoked earlier in that notebook, and I suppose that's why it was readily available for such a proof.
If I comment out earlier deduceInNumberSet() calls that might have invoked the `expRealClosureBasePos` theorem, then the specialization of the more general `expRealClosure` theorem with `Greater(x, zero)` still works and actually uses the asked-for theorem, as shown below:
![image](https://user-images.githubusercontent.com/41027033/75178929-40f59000-56f6-11ea-92a5-e6dfb392e9bc.png)
We can see the specialization now on line 4 of the proof allowing the LHS of the OR being True to make the whole OR to be True.
BUT, if I try specializing the `expRealClosure` theorem as follows (trying to invoke the RHS of the OR condition):

> expRealClosureExampleLHSofOR = expRealClosure.specialize(
>     {a:x, b:y},
>     assumptions=[InSet(x, Reals), InSet(y, Reals), GreaterEq(x, zero), NotEquals(y, zero)])

the effort fails, with the following message:

> SpecializationFailure: Proof step failed assuming {x in Reals, y in Reals, x >= 0, y != 0}: Unmet specialization requirement: (x > 0) or ((x >= 0) and (y != 0)) when specializing |- forall_{a, b in Reals | (a > 0) or ((a >= 0) and (b != 0))} (a^{b} in Reals) with {a: x, b: y}

I've tried wrapping the `GreaterEq(x, zero), NotEquals(y, zero)` portion in an And(), and variations on grouping them as a tuple … but no joy yet. The fact that I can't get the two conditions to “group” in the way the system later lists as the “specialization requirement” makes me wonder if the system simply can't interpret the two conditions as satisfying that RHS of the Or() condition because of some notational difference.

**Comment by wwitzel** [comment]
This was helpful.  I think I know the problem.  It is able to prove (x>=0) in Bool given x>0 (because x>=0 is True), but it may be having problems proving x>0 in Booleans.  Try proving that or adding it as an assumption.

**Comment by wdcraft01** [comment]
Yes, that seems to have solved it: including the InSet(Greater(x, 0), Booleans) as an assumption gives:
![image](https://user-images.githubusercontent.com/41027033/75183494-e9f4b880-56ff-11ea-9b8e-791c09465ba4.png)

**Comment by wwitzel** [comment]
Great!  We'll just have to get it to automatically conclude that (x>0) in Bool (or < or >= or <=) when x in Real.  That shouldn't be too hard.

**Comment by wwitzel** [comment]
I'm closing out this issue.  Much has improved with "readily_provable" not implemented (#289).
