### ISSUE TITLE
sqrt method instead of Sqrt class

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#108]
We should make sqrt simply be a style option when the exponent is 1/2 rather than a separate Expression class.  This would be similar to the way we now have the 'frac' method and the 'subtract' method.

**Comment by wdcraft01** [comment]
I am handling this inside the branch 104-Augment-Exp-class-with-deduceInNumberSet-method. About ready for a pull-request/review.

**Comment by wdcraft01** [comment]
This has been completed, initially handled in the branch 104-Augment-Exp-class-with-deduceInNumberSet-method, then modifed by WW and pulled into origin/master by WW.
