### ISSUE TITLE
Update modular context axioms and theorems

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#113]
The modular context needs translating and updating from older system, meaning taking the older axioms.py and theorems.py and transferring/updating them into the `_axioms_` and `_theorems_` ipnb's. This will be helpful in continuing the more general update of the QPE context because we have some related theorems there which use ModAdd, which in turn is defined using Mod. The modular context includes the following classes: Mod (defined in mod.py), Abs (defined in abs.py), and ModAbs (defined in mod_abs.py), all of which are extension of the Operation class. The older to-be-updated axioms and theorems are contained in the context's axioms.py and theorems.py files. Related Issue: #97.

**Comment by wwitzel** [comment]
As I mentioned in the "pull request" review associated with this issue, we may want to split off the "absolute value" axioms/theorems.  I'm leaning toward making a proveit.number.abs_val context (or "absolute_value" or "abs_value").  What do you think?

**Comment by wdcraft01** [comment]
Corresponding branch 113 was merged into master on 3/16/2020 (see Issue #113 and pull request #115) and branch deleted.
