### ISSUE TITLE
Split off an absolute_value context from number/modular context

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#119]
The `number/modular` context has recently been updated, translating and updating a number of theorems and axioms from older files into newer .ipynb files. The `Abs` class (defined in number/modular/abs.py) and related absolute value theorems are currently folded into the modular context and can probably be usefully separated out into a separate number/absolute_value context. Related Issue: #113.

**Comment by wdcraft01** [comment]
Submitted a pull request review to WW on the associated branch 119-split-off-absolute_value-context from-modular-context.

**Comment by wwitzel** [comment]
Merged via 119-split-off-absolute_value-context-from-modular-context.
