### ISSUE TITLE
Add deduceInNumberSet() method to Mod class

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#121]
Similar to the `deduceInNumberSet()` method found in the `Add` class, or the more recently-added `deduceInNumberSet()` method in the `Exp` class, the `Mod` class can also use a `deduceInNumberSet()` method to help automation or semi-automation of proofs. Both the `Add` and `Exp` classes can serve as good examples. Related issues: #97, #113.

**Comment by wdcraft01** [comment]
Have gone ahead and addressed this issue in branch 119-split-off-absolute_value-context … as well as generally updating the Mod class and the ModAbs class and adding a deduceInNumberSet() method to the ModAbs class as well.

**Comment by wwitzel** [comment]
I believe this is reasonably implemented now.
