### ISSUE TITLE
conform to PEP8 style

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#127]
We can use a tool like "autopep8".  We just need to schedule a time to do this since it will impact code everywhere.

**Comment by wdcraft01** [comment]
@wwitzel @jmadridlarra  I have started looking into PEP08 python formatters and related matters. Some cool and useful things out there, and I'll comment soon about them. This is just a quick note about a related tool that I hadn't really been aware of (I suspect WW or JML or both have mentioned this to me, but I didn't absorb it at the time or it's been long enough ago I simply forgot about it): **pycodestyle** (which replaces the older pep8 utility). This is actually kind of cool and could be helpful even before we adopt any pep08 style formatter. For example, here is some statistical output it produces when run Prove-It's build.py code:

```
> $ pycodestyle --quiet --statistics build.py  
> build.py 
> 7       E225 missing whitespace around operator 
> 11      E228 missing whitespace around modulo operator 
> 24      E261 at least two spaces before inline comment 
> 6       E262 inline comment should start with '# ' 
> 19      E265 block comment should start with '# ' 
> 9       E302 expected 2 blank lines, found 1 
> 4       E305 expected 2 blank lines after class or function definition, found 1 
> 116     E501 line too long (83 > 79 characters) 
> 1       E722 do not use bare 'except' 
> 53      W291 trailing whitespace 
> 36      W293 blank line contains whitespace 
> 1       W605 invalid escape sequence '\l' 
```

The `--statistics` flag is what produces the statistical count summary like that, and the `--quiet `flag suppresses the detailed line# output is also produces identifying exactly where each formatting issue arises. I think there are other flags to allow suppression of certain errors and/or reporting only on certain types of errors.

**Comment by wwitzel** [comment]
We performed a camel-case to snake-case conversion and ran autopep8 --aggressive --aggressive.
