### ISSUE TITLE
Show minimal "presuming" info to replace the "presuming" list.

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#153]
Providing "presuming" information in theorem proofs is a way to ensure there is no circular dependencies among theorems regardless of the order in which they are proven.  It's kind of a pain to get this right, however.  It is much easier to simply presume everything, or large categories of things.  But you can't always do this.  You'll be forced to be more specific as you proceed in that fashion because Prove-It needs enough information to disentangle the DAG of theorem dependencies.  Specifically, if theorem A was proven presuming everything and theorem B needs A, it won't be able to presume everything as well.

To avoid this, we could print out a list of minimal presumptions, along with instructions, when %qed is performed.  Then you can take that list and past it at the top of the theorem proof notebook as the "presuming" list.  That will allow a user to start by presuming everything (or full branches of packages/theories) if they wish but then they will revise it to just the list of theorems that are specifically needed, avoiding future issues.

**Comment by wdcraft01** [comment]
This sounds like an excellent idea.

**Comment by wwitzel** [comment]
Thanks Hoss.  We also may want to make a capability to specifically exclude things from being presumed as a convenient means of presuming almost everything initially, except for certain things where there could be a circular logic issue.  Then you'd still update it to the minimal list (and no longer user the exclusions) after you get the proof to go through.

**Comment by wwitzel** [comment]
Also, to ensure enforcement, we can simply make %qed fail until the "canonical" presuming list is adopted.  It will say something to the effect of "Congratulations, you have a proof for your theorem.  Just do this one thing before it is official ..."

**Comment by wwitzel** [comment]
Note that there are times when a theorem may be used incidentally during the proof construction but isn't used in the proof.  Where I've seen this happen is in computing the length (number or entries) of an ExprTuple to know how to instantiate some other theorem, but the theorem used to compute the length isn't necessarily needed directly.  Maybe other situations like that will come up.  Perhaps the "minimal" presuming info should include these incidental usages to avoid future frustration.

**Comment by wwitzel** [comment]
However, we should not include side-effects that aren't actually needed.

**Comment by wwitzel** [comment]
@wdcraft01 had a good suggestion of making a link to the "presuming" list since those lists can be long.  We want information available but in a non-obtrusive fashion.  I'm also thinking that it could just put the data in a file somewhere, generated when you run %qed.  Things to consider.

**Comment by wwitzel** [comment]
Also, let's not have implicit presumptions based upon the order of the theorems in the theorems page.  That turns out to be a real nuisance for organizing theorems.

**Comment by wdcraft01** [comment]
@wwitzel So does that mean we would need to explicitly presume any desired theorems even from the same package? Or do you have something else in mind? This also sounds like a change that might be painful in the near term to implement — do we have a cascade of theorems already established that implicitly presume all the previously-listed theorems in the package?

**Comment by wwitzel** [comment]
I don't expect we would be able to implement this right away.  We need to be clever with the implementation to update everything.  I'd implement the other features first so we can update the theorems that implicitly presume previous theorems in the package.  I'm thinking that the %qed will automatically populate some file with the full list of needed presumptions.  After that, everything will be explicit.  The future mode of operations would be to initially presume everything EXCEPT what you know you want to avoid when you first generate the proof, but %qed will automatically convert it to an explicit list of precise theorems to avoid future issues.  The one problem with this is dealing with moving/renaming theorems.  But that is already a bit of a nuisance and this won't really make it any worse.

**Comment by wwitzel** [comment]
This has been implemented with the merger of the recent "overhaul#" branches.
