### ISSUE TITLE
Establish foldAsForall() method for enumerated Sets

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#158]
As far as I can tell, only the Booleans domain currently has a `foldAsForall()` method, but the method (and related theorem(s)) could be useful for the enumerated Set class as well since enumerated Sets often appear as domains in Forall &forall; expressions. @wwitzel will have better insight than I about whether or not this would be an appropriate addition to the enumerated Set class.

**Comment by wwitzel** [comment]
That makes sense to me.  We may want to change the "fold" terminology, though.  It is essentially "proof-by-cases" so we may want to switch to terminology along those lines at some point.
