### ISSUE TITLE
'superset' and 'greater than' as style variants of 'subset' and 'less than'

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#180]
Should we simply make 'superset' just a different style option of 'subset' and make 'greater than' just a different style option of 'less than'?  Then we wouldn't be duplicating theorems and classes, etc.  Is there a good reason not to do this??

**Comment by wdcraft01** [comment]
This sounds promising but I'm not sure how to carefully evaluate the idea. A couple related questions or issues come to mind:

(1) I agree that an alternative-style approach to supersets might be quite useful in reducing multiplicity and generation of theorems, and in reducing the generation of classes, thereby simplifying (or at least streamlining) the set_theory containment context (and perhaps other related contexts?).

(2) How easy or natural is it for a general user to learn or be aware of this way of doing things, and how easy or natural will it be to actually use? For example, if I am working with some things involving superset notation, is it trivial or perhaps an annoying hassle to conceive everything in terms of subsets and invoke some style setting?

(3) More generally, how would going with such a style option affect the attractiveness/usability for a general user? Despite the utility of the style option approach for reducing clutter and conceptual duplication, would it still be useful to maintain the transparency of the superset and related classes and theorems?

**Comment by wwitzel** [comment]
Good questions, @wdcraft01 .  How I would imagine implementing this is that there would be a "Subset" class and a superset function.  The "superset" function (lowercase is intentional) which would create a Subset object but change it to a superset style.  This is consistent with "Add" vs "subtract" and "Div" vs "frac".  The upper/lower case convention makes it clear which one is the actual class versus a function that creates the object with an alternate style.  Addressing (2), you can construct theorems using "superset" or "Subset" at will and it shouldn't really matter that the supersets are really Subsets.  But, are there methods that make less sense when called on a superset which is really a Subset?

**Comment by wwitzel** [comment]
If you want to give this a try, @wdcraft01 , and want to assign yourself, go for it.  Unless you think we should have more of a discussion -- feel free to bring it up with Deepak and/or Hoss.  I think this is the way to go, just like "subtract" and "frac".
