### ISSUE TITLE
innerExpr().digits doesn't work right for DecimalSequence

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#187]
We noticed this problem in a branch that @jmadridlarra was working in.  It seems to be an InnerExpr bug.  DecimalSequence has a 'digits' attribute that is the same as 'operands' but they don't act the same for an InnerExpr.

**Comment by wwitzel** [comment]
I had a similar problem with Mult.factors.  The fix was fairly simple.  In Mult.__init__, I changed
  self.factors = operands
to
  self.factors = self.operands
after Operation.__init__.

I imagine a similar fix should work for DecimalSequence.digits.

**Comment by jmadridlarra** [comment]
This should be fixed now in branch 170-RoR_reductions
