### ISSUE TITLE
Common expression database dependencies

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#197]
We'd like to improve our solutions to the chicken-and-egg problem that may arise when common expressions are imported within packages (e.g. __init__.py) but the database is not up-to-date with the common expression notebooks.  For example, the common expressions notebook og the "rationals" package defines Rationals, but it also imports things from the number package which imports Rationals -- that's the chicken-and-egg problem.  Additionally, there is the issue of building the common expression database from scratch when common expression notebooks depend upon each other.  Here's are solutions to both of these issues:

1. Make new magic commands to go at the top of each common expression notebook (as well as axiom and theorem notebooks for consistency).  These would go in place of the "defaults.automation = False" command which could be effected by the new magic commands.  These would let Prove-It know which type of notebook it is running.  It already figures out what theory package it is in based upon the current working directly, but it needs to also know which type (common, axioms, or theorems).  By knowing whether it is a common expression notebook, it knows to essentially ignore any imports from that package (axioms and theorems can depend upon common expressions, but common expressions can't make use of axioms or theorems).  It can just return "None" for those items.  So, when Rationals is imported from the common expressions notebook of the "rationals" package, it will just be set to None which is fine since it shouldn't be used in that notebook until it is defined.  This resolves the chicken-and-egg problem.

2.  Apart from attempts to import common expressions from the same package, which are ignored and yield None, when there is a failed import of a common expression, we'll raise an exception but first create a text file called "failed_import.txt" within the __pv_it folder corresponding to the notebook that we are running which indicates which file it failed to import from.  In the build script, when the notebook fails, it will look for a "failed_import.txt" file and know that it must complete this other notebook first before trying again.  It will keep doing these retries until they are all done or until the only unfinished notebooks are ones with "failed_import.txt" files.  In the latter case, it will know that there is a circular dependence and raise an exception.

**Comment by wwitzel** [comment]
What do we call the new magic commands?  Perhaps this:
%common_expression_notebook
%axiom_notebook
%theorem_notebook

Any other ideas @wdcraft01 or @jmadridlarra ?

**Comment by jmadridlarra** [comment]
Those look good to me.  I was trying to think of some way to differentiate further from the "%begin" magic command, but this new magic command isn't really performing a process, but instead passing along some information.  Is that correct?  

If so, I think it makes sense to just have the name as you indicated above which is different than the verb "begin" that is used later.

**Comment by wwitzel** [comment]
I also thought about moving the "%begin" commands to the top and having it play both roles.  It's tempting.  I don't think it would make a difference in most cases.  The only thing is that assignments at the end of cells between %begin and %end go  into the database as common expressions, axioms, or theorems respectively for %begin/end common, %begin/end axioms, and %begin/end theorems.  So the only time it would be an issue is if you want to assign a variable to an expression within the notebook that you don't want to go in the database.   That never really happens, but could it cause a hang-up for anybody in the future?  What do you think?

**Comment by jmadridlarra** [comment]
Ideally, it would be nice to combine the two into one command, but since their purposes are different, I think it makes sense to keep them separate.  The only problem I see with keeping them separate is user confusion about their purpose which is why I think the naming needs to be differentiated.  Perhaps in addition to the current naming convention, we add a comment before each command?  Maybe something along the lines of:

`#Tells Prove-It that this is a Common Expression Notebook`
`%common_expression_notebook`
`...`
`#everything after this command will be defined as a common expression and stored in the Prove-It database for further usage`
`%begin common`

**Comment by wwitzel** [comment]
Good suggestion.  Thanks @jmadridlarra !

**Comment by wwitzel** [comment]
I think the new magic commands should use this form actually:
%common_expressions_notebook
%axioms_notebook
%theorems_notebook

**Comment by wwitzel** [comment]
Implemented with overhaul# branches.
