### ISSUE TITLE
Add Index- and Summand-Simplification Options to Shift, Split, Join Sum methods

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#224]
The `Sum.shift()`, `.split()`, and `.join()` methods can be augmented to further process/simplify the new index lower- and upper-bounds and summands, and this can be achieved using a pre-processing of the new indices and/or new summand using a shallow simplification method and then passing the resulting equivalences to the eventual theorem instantiations using the recently-established reductions argument. As I write this, I have already implemented this idea in the `Sum.shift()` method with some success (with some testing performed in the work on a proof for a QPE-related theorem). We should now follow through with implementing this in the `.split()` and `.join()` methods as well and look about for other class methods where this process (pre-simplification and passing along results as a reduction in an instantiation call) would be useful.

**Comment by wwitzel** [comment]
Appears to be implemented, stable, and pulled into master.
