### ISSUE TITLE
Iterations as a list rather than an object

### ISSUE THREAD

**Issue by jmadridlarra** [PyProveIt/Prove-It#24]
_from  proveit.logic.boolean.conjunction._theorems_ import eachInBool
expr = eachInBool.explicitInstanceExpr().explicitConditions()[0].element
expr: A_{1} and … and A_{m} and B and C_{1} and … and C_{n}
expr.deriveInPart(1, assumptions=[expr])_

Maybe this should simply raise an exception when given a Python number, but it could have more interesting functionality when given a Prove-It expression.  In that case, we may want to decide whether to use “base 0” or “base 1” (is the first element indexed as “0” or “1”).  Then suppose we do
_expr.deriveInPart(num(2), base=0, assumptions=[expr])_
then maybe the proper behavior is to prove one of these:
 
_{m in Naturals, m > 1} |- A_{2}
{m ==1} |- B
{m ==0, n in Naturals, n > 0} |- C_{1}_
 
depending upon which of these cases can be proven under the given assumptions.

**Comment by wwitzel** [comment]
There are a number of theorem-instantiating methods that need to be updated to properly treat instances when operands are ExprRanges (And, Or, Add, Mult, etc).

**Comment by jmadridlarra** [comment]
NOTES: After a discussion to revisit this issue:

1) Use Len() rather than len() (Prove-It method rather than python method) to count the number of elements in the expression when instantiating. This is because an ExprRange (ex. A1...Am) is len(A) = 1 and Len(A) = m. There is still hard code that uses len() instead of Len() as well as some code that uses Len(), but has not been tested (conjunction, add, etc.)

**Comment by wwitzel** [comment]
This issue seems to be outdated.
