### ISSUE TITLE
DecimalSequence.deduce_in_number_set(Integer) works for num(11) but not for num(10)

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#248]
I noticed that the following works fine:

`num(11).deduce_in_number_set(Integer)`

but that the following does not work:

`num(10).deduce_in_number_set(Integer)`

giving the interesting failure message:

> InstantiationFailure: Proof step failed:
> Attempting to instantiate |- forall_{n in NaturalPos} [forall_{a_{1}, ..a_{_a}.., a_{n} in NaturalPos} (#(a_{1} ~ ..a_{_a}.. ~ a_{n}) in NaturalPos)] with {n: 2, a: (1, 0)}:
> Unsatisfied condition: 0 in NaturalPos

Apparently despite the leading '1' digit, the method is still only expecting the following digits to also be in NaturalPos instead of Natural? Part of the error trace has the following:

> ~/Desktop/Prove-It/packages/proveit/numbers/numerals/decimals/deci.py in deduce_in_natural_pos(self, **defaults_config)
     90     def deduce_in_natural_pos(self, **defaults_config):
     91         from . import deci_sequence_is_nat_pos
---> 92         return deci_sequence_is_nat_pos.instantiate(
     93             {n: self.operands.num_elements(), a: self.digits})
     94         # from proveit import ProofFailure

suggesting we might could utilize another similar closure theorem where the condition on the DecimalSequence #(a_1 a_2 … a_n) is such that the leading digit a_1 is in NaturalPos and the remaining digits can be Natural, producing a sequence corresponding to a NaturalPos.

**Comment by wwitzel** [comment]
Fixed and pulled into master.
