### ISSUE TITLE
Add Forall.relabel() method to work in the same manner that Forall.specialize() works

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#25]
In particular, add the `Forall.relabel()` method to work in the same manner that `Forall.specialize()` works so that a call to `relabel({x:y})` on a redundantly-nested `Forall` object such as `redundantInstanceVarExpr = Forall(x, And(Px, Forall(x, Qx)))` will relabel the outermost x instead of all xs. ALSO consider more generally looking at and possibly modifying the KnownTruth `relabel()` method so that it perform similarly (i.e. relabels the outermost variable instead of all same-named variables and/or provides a means of choosing the level of nesting in which to perform the requested relabeling).

**Comment by wwitzel** [comment]
This is essentially subsumed by other changes we want to make w.r.t. instantiate and relabel.
