### ISSUE TITLE
Develop numbers.logarithms sub-package

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#265]
The numbers.logarithms sub-package is relatively undeveloped and in particular the Log class needs deduce_in_number_set() and deduce_number_set() methods as well as accompanying closure theorems. As I write this, I have already started the Log.deduce_in_number_set() and Log.deduce_number_set() methods, but with very limited functionality. The figure below can be helpful when considering a few more-specific closure theorems for Logs.

![image](https://user-images.githubusercontent.com/41027033/155425930-31c2569f-974f-4909-9130-3d8e60b1f0a8.png)

**Comment by wwitzel** [comment]
Implemented sufficiently for current needs and in master.
