### ISSUE TITLE
Augment Exp.bound_via_operand_bound() for exponent operand_relation

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#266]
Currently the Exp.bound_via_operand_bound() accepts only an operand_relation argument that relates to the Exp base, allowing us to make bounding concusions such as x^a < y^a given that x < y (and assuming some other constraints). It's useful of course to also deal with operand relations involving the exponent of the Exp, so that, for example we might have x < y and derive a^x < a^y (with suitable constraints).

**Comment by wwitzel** [comment]
Appears to be implemented, tested, and in master.
