### ISSUE TITLE
Augment Ceil class with bound_via_operand_bound() method

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#267]
Unlike several of our other NumberOperations (such as the Exp and Log classes), our Ceil (and the related Floor and Round) classes have not be augmented with the bound_via_operand_bound() method, which would then link up nicely with the more general NumberOperation.deduce_bound() method.

**Comment by wwitzel** [comment]
Appears to be implemented and tested and in master.
