### ISSUE TITLE
Proof of greater_eq ineq reverts to standard LessEq format in formal proof

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#268]
Recent work on a greater_eq theorem as shown here:

![image](https://user-images.githubusercontent.com/41027033/155637549-402b4a4e-1b7a-4c22-b023-d1b391e638b7.png)

resulted in an accepted formal proof with the following result:

![image](https://user-images.githubusercontent.com/41027033/155637572-82e6863b-8c3e-47dc-95fb-7edc190de5b3.png)

meaning that the formal proof is displaying in the “standard” LessEq format rather than the original greater_eq format specified in the actual theorem.

@wwitzel writes that “That should be easy to fix.  It would just be a matter of changing the ‘qed’ method to change the style to the theorem style.”

**Comment by wwitzel** [comment]
I gave a 1-liner to @wdcraft01 that should fix this.  He will test it.

**Comment by wwitzel** [comment]
This has been fixed, I believe.
