### ISSUE TITLE
Implement Max/Min simplification() methods

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#275]
The Max and Min classes have deduce_in_number_set() and deduce_number_set(), but that's about all, and it would be useful to develop these classes further --- for example, the Min 'function' is used in the axiomatic definition of the ModAbs NumberOperation and the Max 'function' could be useful in defining bounds on Abs operations. For that matter, Max and Min classes could implement the bound_via_operand_bound() method and be changed from Functions to NumberOperations.
As an example, a helpful Abs-related theorem might be: Forall_{x \in {a, b}} |x| <= Max(|a|, |b|), and some very simple simplification() implements could look for opportunities to reduce Max(a, b) to a or b if we know something about the relative numerical values of a and b (for example, they could be literal numbers, or they could belong in disjoint sets, etc).

**Comment by wwitzel** [comment]
Presumably in good shape now.
