### ISSUE TITLE
Improve definitions, simplifications of binary Max and Min

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#281]
My current axiomatic definitions for (binary) Max and Min are as follows:

![image](https://user-images.githubusercontent.com/41027033/158039091-b1ae4faf-bf89-45c0-8ce7-08a800090614.png)

![image](https://user-images.githubusercontent.com/41027033/158039098-e26a47de-c421-4f31-bf39-0bd3b8a58f16.png)

which are working fine, _except_ during some routine testing I realized they have an unfortunate and counter-intuitive failure to "evaluate" under circumstances when there is a clear Max (or Min) to be had.

Consider what happens, for example, when simplifying Max(a, b) when we know or assume that b >= a. We would quite reasonably expect that to simplify with Max(a, b) = b, but the axiomatic definition will not do that, because it cannot swap the roles of 'a' and 'b' in its definition. So, do we catch this in the definition() and shallow_simplification() methods somehow and switch the roles of the arguments there? Probably using another theorem about Max(a, b) = Max(b, a)?

**Comment by wwitzel** [comment]
This seems to be in pretty good shape right now.
