### ISSUE TITLE
Update theorem proof presumptions to eliminate unnecessary presumptions

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#285]
When updating some QPE proofs recently, I discovered by accident that the presumptions can often have numerous unnecessary items — I suppose these can be left over from previous versions of the proof, where newer versions of the proof end up using some subset of the presumptions used in an earlier version of the proof. Unlike cases in which we get an error message when a newer version of a proof requires a previously-un-presumed theorem/axiom, the making of some presumption unnecessary does not prompt any error message and thus can lead to unwanted items in the list of presumptions.

**Comment by wwitzel** [comment]
I believe what you are seeing is presumptions coming from side-effects.  This is what I've attempted to address is #258, but it's tricky.  Let's close this issue unless you think this is something different.

**Comment by wdcraft01** [comment]
I don't know where such presumptions are coming from — I don't understand how they might be coming from side-effects. I only became aware of the issue recently when cleaning up and performing some git commits and discovering several theorem proofs for which the presumptions page was showing up as needing to be re-saved, apparently after I had had to clear the presumptions and re-run the proof notebook, and the new commit consisted entirely of some subset of the presumptions that were now unnecessary (i.e. appearing as deleted from the file), despite not having to commit a new version of the proof notebook itself. Would that be related to side-effects? I don't yet see the connection --- you think there was an underlying system change that caused fewer side-effects to be produced? Or a system change causing side-effects to no longer appear in the presumptions? Is that what you mean?

**Comment by wwitzel** [comment]
Obsolete with Issue #300 .
