### ISSUE TITLE
Transitivity sort bug that occurs randomly.

### ISSUE THREAD

**Issue by jmadridlarra** [PyProveIt/Prove-It#39]
The error, shown below, is from the terminal after running build.py.  It seems like a regular proofFailure error.   However, when the disjunction demonstrations are run again they run without error.  I double checked the specific cell that the error is referring to and even reran it, but I am unable to reproduce the error below in the notebook.  Wayne says "It looks like a problem in the "transitivity sort" routine, or related to that.  I suspect it happens somewhat randomly rather than being a difference between build.py vs direct execution."

Executing packages/proveit/logic/boolean/disjunction/_demonstrations_.ipynb
Traceback (most recent call last):
  File "build.py", line 762, in <module>
    build(execute_processor, context_paths, all_paths, args.noexecute, args.just_execute_proofs, args.just_execute_demos, args.just_execute_expression_nbs)
  File "build.py", line 661, in build
    executeAndExportNotebook(execute_processor, full_path, no_execute=no_execute)
  File "build.py", line 418, in executeAndExportNotebook
    nb = execute_processor.executeNotebook(notebook_path)
  File "build.py", line 361, in executeNotebook
    self.preprocess(nb, resources, notebook_dir)
  File "build.py", line 261, in preprocess
    cell, resources = self.preprocess_cell(cell, resources, index)
  File "/home/jmadri/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 424, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
Or(A,B,C,D,E,F,G,H).deriveInBool(inBool(A,B,C,D,E,F,G,H)).proof()
------------------

---------------------------------------------------------------------------
ProofFailure                              Traceback (most recent call last)
/home/jmadri/Prove-It/packages/proveit/_core_/expression/expr.py in prove(self, assumptions, automation)
    409                     # first attempt to prove via implication
--> 410                     concludedTruth = self.concludeViaImplication(assumptions)
    411                 except ProofFailure:

/home/jmadri/Prove-It/packages/proveit/_core_/expression/expr.py in concludeViaImplication(self, assumptions)
    458         from proveit.logic import concludeViaImplication
--> 459         return concludeViaImplication(self, assumptions)
    460

/home/jmadri/Prove-It/packages/proveit/logic/boolean/implication/implies.py in concludeViaImplication(consequent, assumptions)
    301                         queue.append(local_antecedent)
--> 302     raise ProofFailure(consequent, assumptions, 'Unable to conclude via implications')
    303

ProofFailure: Unable to prove (A or B or C or D or E or F or G or H) in BOOLEANS assuming {A in BOOLEANS, B in BOOLEANS, C in BOOLEANS, D in BOOLEANS, E in BOOLEANS, F in BOOLEANS, G in BOOLEANS, H in BOOLEANS}: Unable to conclude via implications

During handling of the above exception, another exception occurred:

TransitivityException                     Traceback (most recent call last)
<ipython-input-1-015319e51506> in <module>
----> 1 Or(A,B,C,D,E,F,G,H).deriveInBool(inBool(A,B,C,D,E,F,G,H)).proof()

/home/jmadri/Prove-It/packages/proveit/logic/boolean/disjunction/or_op.py in deriveInBool(self, assumptions)
    134         From (A or B or ... or Z) derive [(A or B or ... or Z) in Booleans].
    135         '''
--> 136         return inBool(self).prove(assumptions=assumptions)
    137
    138     def deriveParts(self, assumptions=USE_DEFAULTS):

/home/jmadri/Prove-It/packages/proveit/_core_/expression/expr.py in prove(self, assumptions, automation)
    411                 except ProofFailure:
    412                     # try the 'conclude' method of the specific Expression class
--> 413                     concludedTruth = self.conclude(assumptions)
    414             if concludedTruth is None:
    415                 raise ProofFailure(self, assumptions, "Failure to automatically 'conclude'")

/home/jmadri/Prove-It/packages/proveit/logic/set_theory/membership/in_set.py in conclude(self, assumptions)
     82         # could not prove it through a subset relationship, now try to use a MembershipObject
     83         if hasattr(self, 'membershipObject'):
---> 84             return self.membershipObject.conclude(assumptions)
     85
     86     def evaluation(self, assumptions=USE_DEFAULTS):

/home/jmadri/Prove-It/packages/proveit/logic/boolean/booleans.py in conclude(self, assumptions)
    135         # Use 'deduceInBool' if the element has that method.
    136         if hasattr(element, 'deduceInBool'):
--> 137             return element.deduceInBool(assumptions=assumptions)
    138         raise ProofFailure(inBool(element), assumptions, str(element) + ' not proven to be equal to TRUE or FALSE.')
    139

/home/jmadri/Prove-It/packages/proveit/logic/boolean/disjunction/or_op.py in deduceInBool(self, assumptions)
    396             return binaryClosure.specialize({A:self.operands[0], B:self.operands[1]}, assumptions=assumptions)
    397         else:
--> 398             return closure.specialize({m:num(len(self.operands)), AA:self.operands}, assumptions=assumptions)
    399
    400     def concludeViaExample(self, trueOperand, assumptions=USE_DEFAULTS):

/home/jmadri/Prove-It/packages/proveit/_core_/known_truth.py in specialize(self, specializeMap, relabelMap, assumptions)
    760                     processedSubMap[iVar] = iVar
    761
--> 762         return self._checkedTruth(Specialization(self, numForallEliminations=numForallEliminations, specializeMap=processedSubMap, relabelMap=relabelMap, assumptions=assumptions))
    763
    764     def generalize(self, forallVarLists, domainLists=None, domain=None, conditions=tuple()):

/home/jmadri/Prove-It/packages/proveit/_core_/proof.py in __init__(self, generalTruth, numForallEliminations, specializeMap, relabelMap, assumptions)
    724             generalExpr = generalTruth.expr
    725             # perform the appropriate substitution/relabeling
--> 726             specializedExpr, requirements, mappedVarLists, mappings = Specialization._specialized_expr(generalExpr, numForallEliminations, specializeMap, relabelMap, assumptions)
    727             # obtain the KnownTruths for the substituted conditions
    728             requirementTruths = []

/home/jmadri/Prove-It/packages/proveit/_core_/proof.py in _specialized_expr(generalExpr, numForallEliminations, specializeMap, relabelMap, assumptions)
    871         mappings.update(relabelMap) # mapping everything
    872
--> 873         subbed_expr = expr.substituted(specializeMap, relabelMap, assumptions=assumptions, requirements=requirements)
    874
    875         # Return the expression and conditions with substitutions and the information to reconstruct the specialization

/home/jmadri/Prove-It/packages/proveit/_core_/expression/operation/operation.py in substituted(self, exprMap, relabelMap, reservedVars, assumptions, requirements)
    348         if (exprMap is not None) and (self in exprMap):
    349             return exprMap[self]._restrictionChecked(reservedVars)
--> 350         subbed_operand_or_operands = self.operand_or_operands.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)
    351         subbed_operands = compositeExpression(subbed_operand_or_operands)
    352         subbed_operator_or_operators = self.operator_or_operators.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)

/home/jmadri/Prove-It/packages/proveit/_core_/expression/composite/expr_list.py in substituted(self, exprMap, relabelMap, reservedVars, assumptions, requirements)
    333         subbed_exprs = []
    334         for expr in self:
--> 335             subbed_expr = expr.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)
    336             if isinstance(expr, Iter) and isinstance(subbed_expr, ExprList):
    337                 # The iterated expression is being expanded

/home/jmadri/Prove-It/packages/proveit/_core_/expression/operation/operation.py in substituted(self, exprMap, relabelMap, reservedVars, assumptions, requirements)
    348         if (exprMap is not None) and (self in exprMap):
    349             return exprMap[self]._restrictionChecked(reservedVars)
--> 350         subbed_operand_or_operands = self.operand_or_operands.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)
    351         subbed_operands = compositeExpression(subbed_operand_or_operands)
    352         subbed_operator_or_operators = self.operator_or_operators.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)

/home/jmadri/Prove-It/packages/proveit/_core_/expression/composite/expr_list.py in substituted(self, exprMap, relabelMap, reservedVars, assumptions, requirements)
    333         subbed_exprs = []
    334         for expr in self:
--> 335             subbed_expr = expr.substituted(exprMap, relabelMap, reservedVars, assumptions, requirements)
    336             if isinstance(expr, Iter) and isinstance(subbed_expr, ExprList):
    337                 # The iterated expression is being expanded

/home/jmadri/Prove-It/packages/proveit/_core_/expression/composite/iteration.py in substituted(self, exprMap, relabelMap, reservedVars, assumptions, requirements)
    328                     arg_sorting_relation = None
    329                 else:
--> 330                     arg_sorting_relation = Less.sort(special_points[axis], assumptions=arg_sorting_assumptions)
    331                 arg_sorting_relations.append(arg_sorting_relation)
    332

/home/jmadri/Prove-It/packages/proveit/relation/transitivity.py in sort(RelationClass, items, reorder, assumptions)
    118         assumptions = defaults.checkedAssumptions(assumptions)
    119         if reorder:
--> 120             return RelationClass._transitivitySort(items, assumptions=assumptions)
    121         else:
    122             return RelationClass._fixedTransitivitySort(items, assumptions=assumptions)

/home/jmadri/Prove-It/packages/proveit/relation/transitivity.py in _transitivitySort(RelationClass, items, assumptions)
    523
    524         if len(unique_items)>1 and len(remaining_items)>0:
--> 525             raise TransitivityException(None, assumptions, "Insufficient known transitive relations to sort the provided items: " + str(items))
    526
    527         orig_order = {item:k for k, item in enumerate(items)}

TransitivityException: Proof step failed assuming {A in BOOLEANS, B in BOOLEANS, C in BOOLEANS, D in BOOLEANS, E in BOOLEANS, F in BOOLEANS, G in BOOLEANS, H in BOOLEANS, (1 - 1) = 0, (1 + 1) = 2, 0 < 1, 1 < 2, 1 = (2 - 1), 1 <= 1, (2 - 1) = 1, (2 + 1) = 3, 2 < 3, 2 = (3 - 1), 2 <= 2, (3 - 1) = 2, (3 + 1) = 4, 3 < 4, 3 = (4 - 1), 3 <= 3, (4 - 1) = 3, (4 + 1) = 5, 4 < 5, 4 = (5 - 1), 4 <= 4, (5 - 1) = 4, (5 + 1) = 6, 5 < 6, 5 = (6 - 1), 5 <= 5, (6 - 1) = 5, (6 + 1) = 7, 6 < 7, 6 = (7 - 1), 6 <= 6, (7 - 1) = 6, (7 + 1) = 8, 7 < 8, 7 = (8 - 1), 7 <= 7, (8 - 1) = 7, (8 + 1) = 9, 8 < 9, 8 = (9 - 1), 8 <= 8, forall_{P, x, y | P(y) , x = y} P(x), forall_{P, x, y | P(x) , x = y} P(y), forall_{x, y | x = y} (y = x), forall_{x, y, z | x < y , y < z} (x < z), forall_{x, y, z | x <= y , y < z} (x < z), forall_{x, y, z | x < y , y <= z} (x < z), forall_{x, y, z | x <= y , y <= z} (x <= z), forall_{a, b, c | (a + b) = c} ((c - b) = a), forall_{a, b, c | (a - b) = c} ((c + b) = a)}: Insufficient known transitive relations to sort the provided items: {9, 0, 6, 8, 4, 5, 2, 3, 1, 7}
TransitivityException: Proof step failed assuming {A in BOOLEANS, B in BOOLEANS, C in BOOLEANS, D in BOOLEANS, E in BOOLEANS, F in BOOLEANS, G in BOOLEANS, H in BOOLEANS, (1 - 1) = 0, (1 + 1) = 2, 0 < 1, 1 < 2, 1 = (2 - 1), 1 <= 1, (2 - 1) = 1, (2 + 1) = 3, 2 < 3, 2 = (3 - 1), 2 <= 2, (3 - 1) = 2, (3 + 1) = 4, 3 < 4, 3 = (4 - 1), 3 <= 3, (4 - 1) = 3, (4 + 1) = 5, 4 < 5, 4 = (5 - 1), 4 <= 4, (5 - 1) = 4, (5 + 1) = 6, 5 < 6, 5 = (6 - 1), 5 <= 5, (6 - 1) = 5, (6 + 1) = 7, 6 < 7, 6 = (7 - 1), 6 <= 6, (7 - 1) = 6, (7 + 1) = 8, 7 < 8, 7 = (8 - 1), 7 <= 7, (8 - 1) = 7, (8 + 1) = 9, 8 < 9, 8 = (9 - 1), 8 <= 8, forall_{P, x, y | P(y) , x = y} P(x), forall_{P, x, y | P(x) , x = y} P(y), forall_{x, y | x = y} (y = x), forall_{x, y, z | x < y , y < z} (x < z), forall_{x, y, z | x <= y , y < z} (x < z), forall_{x, y, z | x < y , y <= z} (x < z), forall_{x, y, z | x <= y , y <= z} (x <= z), forall_{a, b, c | (a + b) = c} ((c - b) = a), forall_{a, b, c | (a - b) = c} ((c + b) = a)}: Insufficient known transitive relations to sort the provided items: {9, 0, 6, 8, 4, 5, 2, 3, 1, 7}

**Comment by wwitzel** [comment]
This appears to be a but in the "_transitivitySort" method.

**Comment by wwitzel** [comment]
Fixed.
