### ISSUE TITLE
Better presentation of empty notebooks in the website

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#44]
Ideas: flag as empty?  link to content in sub-packages?

**Comment by wwitzel** [comment]
Perhaps we want to show all axioms of the theory and sub-theories, etc. on the "theory" pages.  And maybe a link to a page of theorems similarly (including sub-theory theorems, etc.).

**Comment by wdcraft01** [comment]
Just to add a bit for clarification — here is an example “theory” page for the entire logic theory package, which of course has links showing for common expressions, axioms, theorems, and demonstrations, but those axiom pages, etc., are actually empty or almost-empty, with all the axioms, theorems, etc., buried on more specific pages within sub-theory folders (like sets, booleans, etc).

![image](https://user-images.githubusercontent.com/41027033/100947070-0fe68f00-34c2-11eb-9cc6-4fda404dd69e.png)

Wayne is proposing that such a page as pictured above would automatically include an explicit listing of the axioms in the entire enfolding theory package, which in the case above would include all the axioms that would be found at the proveit/logic level (if any) and all the axioms that would be found at each of the sub-theory (and recursively below) folders on boolean (eventually to be called booleans), equality, and set_theory (eventually to be renamed as sets).

It will be interesting to consider how to organize the listing of all the axioms in the theory tree.

**Comment by wwitzel** [comment]
My inclination is to go in the order of the sub-theory listing, lexicographically according to that.  Hopefully I'll demonstrate this soon and you can see what you think.

**Comment by wwitzel** [comment]
We now list all of the axioms of the theory and sub-theories, etc.  Joaquin is working on a better version with tabs for axioms and theorems and an expandable "accordion" for sub-theories.
