### ISSUE TITLE
"instantiate" and "skolemize"

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#49]
After some recent discussions (involving Bob's structured proof for sqrt 2 which involves invoking constants as instantiations of existential operators, and Hoss's comments about relabeling as he is looking closely and revising tutorials), and some google lookups leading me to terminology in "natural deduction" systems, I propose to make the following changes to our derivation system.

Guided by a desired to make a system that is intuitive, elegant, and flexible, rather than purely minimalist, I think we should add derivation rules for existential quantification in addition to the derivation rules we have for universal quantification.  I'm also now onboard with changing "specialize" to "instantiate".  There is a nice symmetry (w.r.t. universal and existential derivation rules) to the language I'm finding is used in natural deduction:
universal instantiation (what Prove-It had been calling "specialization")
existential instantiation (also known as skolemization)
universal generalization (what Prove-It had been calling "generalization")
existential generalization (currently effected by the existenceByExample theorem in Prove-It).
I propose we adopt these new names as the "step type" names listed in proof tables.  We may want to reduce the font size and make it wrap to two lines in these HTML tables since these are longer names.  To invoke them, however, we need simple and distinct names.  I propose:
"instantiate" (instead of "specialize")
"skolemize" (as proposed by Deepak for existential instantiation)
"universalize" (instead of "generalize")
"existentialize" (for existential generalization).

Furthermore, "relabel" as a type of derivation step is somewhat obsolete with the recent change to make Lambda parameterization be regarded as generic (e.g., "forall_x P(x)" is now regarded to be the same as "forall_y P(y)").  We should still have "relabel" as a command for Expression (as well as InnerExpr objects as Hoss and I had discussed) for transforming Expression objects to other Expression objects regarded to be equal but with a different "style" (with respect to Lambda parameters).  But this is no longer a derivation step.

Instead, we could have extra derivation steps for "implicit universal instantiation" (abbreviated as "implicit univ. instantiation") and "implicit existential instantiation" (abbreviated as "implicit exist. instantiation") which is the same as doing a "generalization" and then "instantiation" all in one step (without doing anything fancy with the "generalization" part).  We could still use "instantiate" and "skolemize" as the method names to do this, but just a different context (when calling "instantiate" on a Forall Expression/KnownTruth, we do "universal instantiation" otherwise we do "implicit universal instantiation"; likewise when calling "skolemize" on an Exists Expression/KnownTruth, we do "existential instantiation" otherwise we do "implicit existential instantiation".  Here is an example of how it would work.  You could use "implicit universal instantiation" to go from
{A, A => B} |- B
to
{A, A => t} |- t
where 't' is any expression.

One more thing, let's change the "substituted" Expression methods to "instantiated".

Changes to many file will result from this.  Let's do the main core changes in a branch called "instantiate_and_skolemize" and include a script for automatically making name replacements in all of the other files (e.g., just a "sed" command in a "bash" script would be good).

**Comment by wwitzel** [comment]
Bob thinks we shouldn't bother with "existential generalization" (just enable it via a theorem like existenceByExample), we should retain "generalize" for universal generalization, and just add skolemize.  Maybe he is right.  I'm pretty sure we do want to add "skolemize" (maybe calling it the "skolemization" derivation rule), and I am on board with changing "specialize" to "instantiate" (and "substituted" to "instantiated", reserving "substitute" for equality-based substitution).  So maybe go with the other parts of the plan as described above.

**Comment by wwitzel** [comment]
The thinking now is going in the direction of scrapping Skolemization as a fundamental derivation step, coming full circle.  The objection started when Deepak saw that our implementation of Skolemization gave us things like
{\exists_x P(x)} |- P(x*)
where x* is understood to be a Skolemization constant and must not be used previously.  I think that we agree that we can implement machinery that does this in a valid way (won't lead to contradictions that do not otherwise exist), but Deepak and Bob are both uneasy in allowing such a KnownTruth to be proven and presented in this manner.  Instead, they both say they would prefer a derivation starting from
{P(x*}} |- P(x*)
and deriving some contingent truth \alpha:
{P(x*)} |- \alpha
and then using \exists_x P(x) to eliminate the P(x*) assumption.  This can be accomplished without any new core machinery via the following theorem:

\forall_{P, Q, \alpha} [\exists_{x | Q(x)} P(x) and \forall_{y | Q(y), P(y)} \alpha] => \alpha

What should we call this?  Skolemization?  SkolemElim?  Cast your vote for one of these or write-in your own.

One nice thing about this approach is that it automatically addresses the issues we have been discussing regarding the dependencies of Skolem constants.  Consider the example Deepak recently posited in an e-mail.  Prove
{ \exists_y \forall_x P(x, y) } |- \forall_x \exists_y P(x, y)
but show that you cannot go the other way.  Let's consider the proof without adding Skolemization machinery as a basic step.  The proof works as follows:

By assumption:
{ \forall_x P(x, y*) } |- \forall_x P(x, y*)
Now instantiate x to x*:
{ \forall_x P(x, y*) } |- P(x*, y*)
Apply the existenceByExample theorem to derive
{ \forall_x P(x, y*) } |- \exists_y P(x*, y)
Generalize y*:
|- \forall_{ y* | \forall_x P(x, y*) } \exists_y P(x*, y)
apply the SkolemElim theorem to derive
{ \exists_y \forall_x P(x, y) } |- \exists_y P(x*, y)
and now generalize x*
{ \exists_y \forall_x P(x, y) } |- \forall_x \exists_y P(x, y)

6 steps.  Using what I was previously proposing in terms of allowing simultaneous universal and existential instantiation and simultaneous universal and existential instantiation, this could be done in two steps.  But it produces statements that Deepak and Bob are uneasy with, and it is wise to heed their uneasiness.

Now let's attempt to go the other way and see where it fails

By assumption:
{ \forall_x \exists_y P(x, y) } |- \forall_x \exists_y P(x, y)
Now instantiate x to x*
{ \forall_x \exists_y P(x, y) } |- \exists_y P(x*, y)
To mimic the strategy before, let's introduce P(x*, y*) by assumption
{ P(x*, y*) } |- P(x*, y*)
To go in the direction of where we want to go, let's now generalize x* to x:
|- \forall_{x | P(x, y*)} P(x, y*)
But we are forced by move the assumption over to a condition since it contains x*.  But now we are stuck.  We can do existenceByExample at this point, but that won't give us what we want; instead, we get
|- \exists_y \forall_{x | P(x, y)} P(x, y)
Let's back up and try something else.  Let's try to apply SkolemElim to { P(x*, y*) } |- P(x*, y*).  First, we need to generalize y*:
|- \forall_{y | P(x*, y) } P(x*, y)
But this doesn't do anything for us.  In order to apply SkolemElim, we need our "alpha" to be independent of y (we cannot instantiate SkolemElim otherwise).

The fact that x* appears free on both sides of the KnownTruth in
{ P(x*, y*) } |- P(x*, y*) 
is what messes us up.  We didn't have that problem in the previous demonstration where we had 
{ \forall_x P(x, y*) } |- P(x*, y*)
In other words, y* was independent of x* previously, but not in the current example.  The good news is that we did not need to add any machinery to track such dependencies.  It is intrinsic to the original rules that require assumptions to move over as conditions when generalize a variable that the assumption depends upon.

Bob is okay with this solution as long as there is convenient manner in which this approach may be applied that is consistent with the way Mathematicians like to think about this.  I propose to do this via a "choose" method in the Exists class and an "eliminate" method in the KnownTruth class.  The "choose" method would automatically generate the appropriate assumptions and add them to default.assumptions, as well as produce the appropriate { P(y*) } |- P(y*) kind of KnownTruth.  It will also remember which existential truth is associated with which variables (acting in the role of Skolem constants).  The "eliminate" method would then be used to apply SkolemElim.  The following is how I envision it working, using the first example above (the indented text represents expected outputs).

init_expr = \exists_y \forall_x P(x, y)
    init_expr  :  \exists_y \forall_x P(x, y)

init_known_truth = init_expr.prove([init_expr])
    init_known_truth : { \exists_y \forall_x P(x, y) } |- \exists_y \forall_x P(x, y)

skolemed = init_known_truth.choose(y*)
    adding \forall_x P(x, y*) to the default assumptions.
    skolemed : { \forall_x P(x, y*) } |- \forall_x P(x, y*)

skolemed.specialize({x: x*})
    { \forall_x P(x, y*) } |- P(x*, y*)

by_example = Exists(y, P(x*, y)).prove() # this *should* automatically invoke existenceByExample
    by_example : { \forall_x P(x, y*) } |- \exists_y P(x* y)

eliminated = by_example.eliminate(y*) # this *should* automatically invoke SkolemElim 
    eliminated : { \exists_y \forall_x P(x, y) } |- \exists_y P(x*, y)

eliminated.generalize({x* : x}) # This would be a nice feature for us to add -- relabel while generalizing
    { \exists_y \forall_x P(x, y) } |- \forall_x \exists_y P(x*, y)

What do y'all think??

**Comment by deepakkapur** [comment]
I need to understand the rules you are using.
How would 
\forall x \exists y P(x, y) |- \forall x \exists P(x, y) 
be proved?

I try to mimic what I understood from above:

P(x*, y*) |- P(x*, y*)
by example
P(x*, y*) |- \exists y P(x*, y)
by generalization on x*
|- \forall x|P(x, y*) \exists y P(x*, y)
what follows after that?

to prove \exists y \forall x P(x, y) |- \exists y \forall x P(x, y)

I assume I will start again with 
P(x*, y*) |- P(x*, y*)
generalize x* to x
|- \forall x|P(x, y*) P(x, y*)

what can I do after this step?
I suppose any of the following:

|- \exists y \forall x|P(x, y) P(x, y)
|- \forall y \forall x|P(x, y) P(x, y)
I do not see how I can get the proof of the known truth I wanted.

**Comment by deepakkapur** [comment]
Related to my above comments/confusion, I state the following:

P(x*, y*) |- P(x*, y*)

I would like to know what x*, y* are. Are they variables or literals (constants)?
Once that is resolved, can they be generalized to variables? if so, what are the restrictions while applying generalization/Skolem_elim derivation rules?

I always get confused by making no distinction between variables and constants/functions (literals). For me, a Skolem constant/function is a literal. 

From P(x*, y*) |- P(x*, y*), it is okay to derive
\forall_x (P(x, y*) |- P(x, y*)) whatever that means

recall our discussion a while ago about free variables appearing on both sides of a known truth being universally quantified.

Since the above is okay, it also follows that
\exists_x P(x, y*) |- P(x, y*) (whatever that means)

But it is not okay to selectively pick x*, y* on one side and then generalize unless restrictions are imposed.

Let us state what those restrictions can be. I will use the equivalent formulation of the known truth above to truth so that I do not have to quantify the known truth:

|- P(x*, y*) \implies P(x*, y*)

Consider the case:

x*, y* are variables, then the above is 
|- \forall_x, y P(x, y) \implies P(x, y)

from which 

|- \exists_x, y P(x, y) \implies P(x, y) or even
|- \exists_x p(x, y*) \implies P(x, y*)
as well as other variations since the matrix P(x, y) \implies P(x, y) is propositionally valid.

Now |- \forall_x, y (P(x, y) \implies P(x, y), I cannot get
|- \forall_x, y P(x, y) \implies \forall_x, y P(x, y) 
as they are two different formulas even though propositionally speaking they are both valid (pardon my some abuse of terminology),
the first being valid because the matrix P(x, y) \implies P(x, y) is propositionally valid, and the second being propositionally valid because of A \implies A.
But if we change the above to:

\forall_x, y P(x, y) \implies Q(x, y)

and the second to:

\forall_x, y P(x, y) \implies \forall_x,y Q(x, y)

the distinction is quite glaring.
These formulas  are very different: the first saying whenever Q(x, y) is true for values of x, y, P(x, y) is also true, but the second one is saying either for some value x, y, P(x, y) is false or for all values of x, y, Q(x, y) is true.

Furthermore as one analyzes further, one can see that 
 I cannot selectively generalize x* or y* (existentially or universally) in the antecedent or consequent of \implies which is what seems to be going on above in Wayne's explanation (unless he has explicitly stated the restrictions).

**Comment by wwitzel** [comment]
Let me answer your first question.   In my 9/11 posting, except for the initial paragraph describing the previous thinking with regard to Skolemization, you should take x, y, x*, y* to be variables.  They are bound locally within each KnownTruth but are regarded to be the same on both sides of "|-" when they are free on both sides.  You can regard the P's and Q's as constants or as variables -- the statements are true either way.

When you say "\forall_x (P(x, y*) |- P(x, y*))", do you mean to have the parentheses span across either side of "|-"?  That is not legal in Prove-It, although you can think of it as an implicit meaning of 
P(x, y*) |- P(x, y*)
That is, you can replace x on both sides.  In any case, using the implication notation avoids all that, so that is fine.

Please take care with your parentheses and include them even when you do not think it is necessary for better clarity.  When you say
|- \forall_x, y P(x, y) \implies Q(x, y)
do you mean
|- [\forall_x, y P(x, y)] \implies Q(x, y)
or
|- \forall_x, y [P(x, y) \implies Q(x, y)]?
Those are very different.  If it is the latter, I agree that you cannot directly derive from this
|- [\forall_x, y P(x, y)] \implies [\forall_x, y Q(x, y)]
But if it is former, you certainly can because the x&y on the left side of the implication are locally bound and distinct from the x&y on the right side of the implication which are free and "arbitrary" variables.

**Comment by wwitzel** [comment]
In any case, let's discuss it on Tuesday.  I'm sure we can clear this up.  Let's try to clear this up and move on.  We need to make some progress.

**Comment by wwitzel** [comment]
Our decision was to do skolemization via axioms/theorems and to rename "specialize" to "instantiate".  The new "instantiate" can instantiate things on the left side of the turnstile as well as eliminate universal quantifiers and do simple relabeling.

**Comment by wwitzel** [comment]
This has been implemented with significant-core-updates merger, but issue #168 is a desired modification of "instantiate" to only instantiate things on the right side and not the left.
