### ISSUE TITLE
Create a Rational NumberSet category

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#60]
Augment our NumberSets categories with a Rational category, probably nestled
in the proveit/number/sets directory along with complex, integer, and real, all of
which can be used as models for the new category.

**Comment by wdcraft01** [comment]
Some notes from Prove-It project meeting 12/13/2019 discussion with WW:
Initially established the rationals subset definition axioms for positive, negative, and non-negative rationals using existential expressions analogous to the original rationals definition axiom, but WW prefers a comprehension (set-builder) approach — e.g. instead of defining Q<sup>+</sup> by (x&isin;Q<sup>+</sup>) = (&exist;<sub>a,b&isin;N<sup>+</sup></sub>(x = a/b)), define it as {q | q >0}<sub>q&isin;Q</sub>. Also provide theorems of the form Q<sup>+</sup>&sub;Q.
Work on this is proceeding inside the craft_edit_containment_demos branch (related Issue #69).

**Comment by wwitzel** [comment]
This was pulled in at some point (e.g. with "Craft edits containment demos").
