### ISSUE TITLE
Implement a Divides(x, y) Operation

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#63]
Implement a Divides(x, y) operation to capture the boolean binary operator x|y. Recall that, for integers x and y, we say x divides y, and write x|y, if and only if there exists an integer k such that y = kx (in other words, x|y iff x is a factor of y). Notice that we have the following properties:
(1) x|y is always true for x = ±1
(2) x|x is always true
(3) x|0 is always true
A Divides operation has been already been partially implemented in the proving_sqrt_2 branch in the proveit/number/divisibility directory in divides.py, in part to implement the sqrt(2)-not-rational proof.

**Comment by wwitzel** [comment]
This was effected through the following axiom:
forall_{x, y} (x | y) = ((y/x) in Z)
