### ISSUE TITLE
Convert Subset class name to ProperSubset class name

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#66]
The `Subset` class has been used to indicate the proper subset &sub; (which is consistent with LaTeX notation as well, using the \subset command), but in many contexts the word "subset" can be ambiguous, often used to indicate the more general inclusive subset &sube; analogous to ≤, but *sometimes* to indicate a proper or strict subset. Our plan is to convert the `Subset` class to be named `ProperSubset`, and to leave the `SubsetEq` class as it is. As an extra, we can consider establishing the names SubsetProper and StrictSubset as aliases to the new ProperSubset class.

**Comment by wwitzel** [comment]
This was addressed when we pulled in "Craft edits containment demos discussion enhancement" and "93 sqrt2 proof" branches.
