### ISSUE TITLE
Tutorialize logic.set_theory.containment demonstrations

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#69]
(1) Tutorialize logic.set_theory.containment demonstrations notebook and along the way:
(2) convert Subset class to ProperSubset class, supplying StrictSubset and SubsetProper as aliases (established as its own issue #66 )
(3) review/edit related axioms and theorems;
(4) establish more of the proofs for various containment theorems;
(5) establish related inBool theorems (for example, for all A, B, SubsetEq(A, B) in Bool)
Work has already been underway for some time on this issue before I created the official issue itself. This is an element issue of Issue #62 .

**Comment by wwitzel** [comment]
The logic.sets.inclusion demonstrations package is more complete and better organized than most.  Let's close out this issue.
