### ISSUE TITLE
Update proveit.number.summation context

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#70]
Update and reinvigorate the `proveit.number.summation` context, theorems of which can also be used as a vehicles for practicing/implementing induction proofs. The topic is also related to the quantum phase estimation (QPE) algorithm and so will contribute to moving related work forward as well.
Some development actions that can begin the effort:

- explore whether any additional axioms are useful or warranted;
- expand the repertoire of theorems;
- use theorems as vehicles for implementing induction proofs;
- update, elaborate on related mechanisms and code as needed;
- begin developing the related _demonstrations_ notebook (currently empty) (related to issue #62).

**Comment by wwitzel** [comment]
We'll call this good for now.
