### ISSUE TITLE
Implement a SetEquiv class

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#71]
It would be helpful to have an explicit way to assert that two sets are equal.
In a project meeting in early October, we discussed the possibility of a SetEquals class along with a standard axiom defining set equality involving non-proper subsets (A = B iff [A is a (non-proper) subset of B and B is a (non-proper) subset of A]). There was concern expressed about whether or not to use a simple = symbol or something else. We do have some set_theory containment context theorems that use set equality A = B as a condition, such as in For all A, B, | A = B [A improper subset of B] (essentially a relaxation theorem), but it's not clear how this would be used without a clear sense of what it means to say that A = B.
Some example applications of set equality involve some classical set-theoretic theorems such as: (a) P(A) = P(B) <=> A = B (where P(X) denotes the power set of X); (b) A x B = C x D <=> A= C and B = D (where X x Y indicates the Cartesian product of sets X and Y).
Some immediate questions for consideration:

1. Where to establish such a setEquals class? Is it best situated in the logic/set_theory context at the same level as containment, intersection, membership, etc? The related classes there are extensions of relations and operations. Is it possible that a SetEquals class might belong logically in the same location as the Equals class?
2. Can we use the established Equals class as a model for a SetEquals class, implementing SetEquals as an extension of a TransitiveRelation?
3. What is the appropriate symbol to use for set equality? Some concern was expressed about using a simple =, instead suggesting something like the congruence symbol. It's probably worth re-iterating in some comment(s) below what the concern is here.

**Comment by wdcraft01** [comment]
Follow-up comments after some discussion in project meeting on Tues 11/05/2019 with WW, RC, and DK:

1. The conceptual concern about the naming and appropriate symbol to use is related to the distinction between two sets being equivalent in terms of items in the set *vs.* two sets being equal in the stronger sense of one being substitutable for the other. WW prefers the SetEquiv nomenclature, with a corresponding symbol like &cong;  (the \cong symbol in LaTeX), meant to capture the equivalence of two sets in the sense of the two sets having the same elements but making no claim about other possible properties of the sets which might make them non-equal (e.g. perhaps one set has a certain ordering imposed on it that is unlike the other set).
2. Will establish the SetEquiv as a TransitiveRelation (but will derive transitivity instead of making it axiomatic).
3. After considering several alternatives, decided that axiomatic definition of SetEquiv will use<br> &forall; <sub>{A, B}</sub> [(A &cong; B) = (A &sube; B &and; B &sube; A)]

**Comment by wwitzel** [comment]
I actually changed the axiomatic definition of set equivalence to:
(A setequiv B) = [\forall_x (x in A) = (x in B)]
I feel this is more at the heart of what it means to be set equivalence.  I'm open to discussing this again though if there is a difference in opinion.
