### ISSUE TITLE
Implement a Power Set

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#72]
The concept of a power set P(S) of a set S is ubiquitous in set theory and it's not clear how to conjure up the concept right now in Prove-It. There are some related concepts and tools in the set_theory context — for example, P(S) is related to set comprehension and the SetOfAll class (although the SetOfAll class generates subsets of a set S, not a set of subsets), and P(S) is similar in some respects to a set function such as cardinality (Card), which conceptually takes a set and produces a real number but isn't really a function as such in Prove-It, instead being more of a representation of the cardinality.
Some initial questions:
1. Would P(S) fit well at the same level as containment, intersection, etc., in the logic/set_theory context? Or might it belong inside one of the folders already there?
2. Would P(S) be conceived of as a function like the Card() function, or more like a special version of the SetOfAll class? Perhaps something completely different?
3. What kind of functionality/methods for a P(S) would be appropriate and useful?
4. What problems or interesting things arise from P(S) being a set of sets rather than a set of … not-sets? Perhaps nothing to worry about or consider here?

**Comment by wwitzel** [comment]
I'm thinking Powerset would just be a basic Operation (like Card) not an OperationOverInstances (like SetOfAll).  The axiom to define it would be something like

powersetDef = \forall_{S, X} [X \in P(S)] = [X \subseteq S]

This is just a conservative extension -- not adding anything fundamental to the theorem.  It should be fine.  But maybe I'm missing some subtlety.

**Comment by wwitzel** [comment]
This has been implemented.
