### ISSUE TITLE
Update simplification/evaluation for division

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#73]
Division (Div) evaluation needs some updating, in part to bring up to similar functionality as recent development of evaluation in addition and multiplication. For example, in some recent work we've had cause to evaluate something like (1*(1+1))/2, which produces 2/2 quite nicely but then fails to go further to get to the 2/2 = 1.
Related issues: Add and Mult evaluation (but not listed as official issues?).

**Comment by wwitzel** [comment]
This is much improved.  Let's call this good for now.
