### ISSUE TITLE
Implement a Cartesian Product

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#74]
Cartesian products are common in set theory and it's not clear how to conjure up the concept right now in Prove-It. There are some related concepts and tools in the set_theory context — for example, a cartesian product is related to set comprehension and the SetOfAll class (although the SetOfAll class generates subsets of a set S, not a set of subsets), and a cartesian product would have commonalities with a power set operator (itself still to be developed).
Some initial questions:

1. Would CartesianProduct fit well at the same level as containment, intersection, etc., in the logic/set_theory context? Or might it belong inside one of the folders already there
2. Would CartesianProduct be conceived of as a function like the Card() function, or more like a special version of the SetOfAll class? Perhaps something completely different?
3. What kind of functionality/methods for a CartesianProduct would be appropriate and useful?
4. Would we conceptualize the cartesian product elements as tuples of the form (x, y) or lists like [x, y]?

Related issues: #72 re: Power Set

**Comment by wwitzel** [comment]
Exponentiated set axioms have been temporarily removed.  They should be added back in.  This is related to Cartesian products.

**Comment by wwitzel** [comment]
There is now a logic.sets.cartesian_products packages which also covers set exponentiation.
