### ISSUE TITLE
Implement Or.concludeViaSome method

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#75]
In the (logical) Or class (defined in logic/boolean/disjunction/or_op.py), we already have the method ``concludeViaExample``, which allows us to conclude that a collection of disjunctions is true based on any one of the operands being True — i.e. A V B V C can be concluded to be true if if we know that B (for example) is True. It may be useful to generalize this to a ``concludeViaSome`` method that allows us to conclude A V B V … V Z is true based on any subset of the operands being true.
Related: This might help with the related issue of proving subset relationships among enumerated sets, for example proving that {1, 3} is a proper subset of {1, 2, 3}.
Also see related issues re: And.deriveSome, and Set.deduceEnumSubset, which I've initially established as separate issues.

**Comment by wdcraft01** [comment]
Some specific suggestions from WW:
> To implement "concludeViaSome", we actually don't need any new theorem.  First, I'd check to make sure that "subset_disjunction" is an instance of Or (otherwise throw a TypeError) and that each of its operands occur as operands in self (otherwise throw a ValueError).  Next, find all of the complementary operands -- operands in 'self' that are not in "subset_disjunction".  I suppose you should be careful about repeated operands in doing this.  Maybe don't worry about that at first.  Assuming there are no duplicated operands at first for simplicity then it is straightforward to create a "complementary_disjunction" and do something like:
binary_disjunction = Or(subset_disjunction, complementary_disjunction).concludeViaLeft(assumptions)
permuted_disjunction = binary_disjunction.disassociate(0, assumptions).disassociate(-1, assumptions)
return self.concludeViaPermutation(permuted_disjunction, assumptions)
But I just made up "concludeViaPermutation", so that would also need to be implemented.  The idea to implement that would be to use commutation as appropriate to go from the passed in "permuted_disjunction" to eventually prove "self".
New theorems could be added to enable doing this with shorter proofs, but I've described something that should be pretty versatile.

**Comment by wwitzel** [comment]
There now exists Or.conclude_via_some and Or.conclude_via_permutation that appear to be implemented.
