### ISSUE TITLE
Implement And.deriveSome method

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#76]
Related issues: #75, #77
In the (logical) ``And`` class (defined in logic/boolean/conjunction/and_op.py), we already have methods ``deriveParts``, ``deriveInPart``, and ``deriveSomeFromAnd``, which provide various possible conclusions from a set of conjunctions such as A AND B AND C … AND Z. ``deriveInParts`` allows the derivation from the conjunction of all the separate operands A, B, C, … Z. ``deriveInPart`` allows the derivation of a specific single operand from the A AND B AND C … AND Z. And ``deriveSomeFromAnd`` is a recent extension by JML that allows the derivation of a single operand even if it is an iteration. The proposed new method ``deriveSome`` should allow the derivation of some specified subset of the A, B, C, … Z (instead of just any single operand).
Related: #75 (Or.concludeViaSome) can be thought of as a “dual” for this proposed And method. Indirectly related to Issue #77 (Set.deduceEnumSubset).

**Comment by wwitzel** [comment]
Handled with significant-core-updates merger.
