### ISSUE TITLE
Implement Set.deduceEnumSubset

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#77]
This issue was raised in the context of developing/discussing machinery to allow conclusions about containment relationships among enumerated sets.
Considering such containment relationships, we might proceed via membership statements and disjunctions, as WW notes:

> … we can think about this w.r.t. subsets instead of disjunctions.  "concludeViaLeft", "concludeViaRight", and "concludeViaSome" all have analogies w.r.t. subset of enumerated sets.  In fact, you'd probably use the disjunction theorems to prove the enumerated subset theorems.The rough analogue to "concludeViaLeft" is something like (universal quantifications are implied):
{A_1, ..., A_i} \subseteq {A_1, ..., A_i, B_1, ..., B_j}
The rough analogue to "concludeViaRight" is something like (universal quantifications are implied):
{B_1, ..., B_j} \subseteq {A_1, ..., A_i, B_1, ..., B_j}
We might as well replace both of these with something more generic:
{B_1, ..., B_j} \subseteq {A_1, ..., A_i, B_1, ..., B_j, C_1, ..., C_k}
We would also need to implement commutation of enumerated sets which can be proven via the commutation of disjunction.
The methods should be enum_set.Set class methods.  They should not be "derive" or "conclude" methods since sets are not booleans.  Maybe a ``deduceEnumSubset`` method and have it take in an ``enum_subset`` parameter.  This would be analogous to ``concludeViaSome``.  Using "deduce" makes it clear that something is being proven, specifically the \subseteq statement.

Related issues: #75, #76 .

**Comment by wdcraft01** [comment]
I have implemented versions of Set.deduceEnumSubsetEq() and Set.deduceEnumProperSubset() that operate on the superset and take as an argument a list of indices for the (proper or improper) subset. Would be nice to extend this now to accept an actual enumerated subset Set() instead of requiring the user to supply the specific indices that produce the (proper or improper) subset.

**Comment by wwitzel** [comment]
This appears to be in good shape.
