### ISSUE TITLE
Relabeling Iterations

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#78]
(1) Relabeling simple variables (not Iters) should be possible without a derivation step (should have a mechanism for this) [provide an example here]
(2) Relabeling iterated variables is more complicated but we should develop/establish a capability here (this will generally require a derivation step).
(3) Would want both these capabilities for inner expressions.
(4) Would also want these capabilities in conjunction with specialization method.
Right now it's set up as a derivation step with the main (specialization) mapping plus the (optional) relabel mapping.
Related Issue #45 .

**Comment by wwitzel** [comment]
Handled with significant-core-updates merger.
