### ISSUE TITLE
Fix OperationOverInstances and SetOfAll formatting issues.

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#80]
Hoss notices that SetOfAll has a formatting error when using multiple instance variables.  There are bugs that need to be fixed.

While we're at it, I thinking of changing the say "multi-domains" are formatted. Instead of
_{(x, y, z) \in X \times Y \times Z}
why not
_{x \in X, y \in Y, z \in Z}?
The latter might be better.

**Comment by wdcraft01** [comment]
The individual version _{x &isin; X, y &isin; Y, z &isin; Z} does often seem to be more straightforward and easier to read. Would the switch eliminate the option of having something like (x, y) &isin; X &times; Y if we wanted it?

**Comment by wwitzel** [comment]
We could always make that a style option if we want to.

**Comment by wwitzel** [comment]
Handled with significant-core-updates merger.
