### ISSUE TITLE
Fix simplification bug

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#81]
Simplifications depend upon the assumptions being used.  For evaluations its different.  Adding more assumptions doesn't change an evaluation since there is only one possible irreducible value evaluation (unless there is a contradiction).  With simplifications, more assumptions can lead to more of a simplification.

**Comment by wdcraft01** [comment]
This issue being addressed in branch 120 along with rounding context issues.

**Comment by wwitzel** [comment]
Branch 120 was merged and addresses this issue.
