### ISSUE TITLE
Fix bug(s) in generic_methods association and commutation bugs

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#87]
There appear to be some bugs in the `groupCommutation()` and `apply_association__thm()` methods in `generic_methods.py`. This is worth further investigation and verification.
More details: Currently it *appears* that:

- the `groupCommutation()` method in `generic_methods` is incorrectly calling the `expr.association()` method, mistakenly using `InitIdx + length` instead of just `length`.
- the `apply_association_thm()` method appears to be incorrectly setting the `end` index value as `startIdx + length` instead of `startIdx + length - 1`.
- there is some odd commutation result appearing occasionally (but this may be the result of the problems already listed above).

**Comment by wwitzel** [comment]
I found an example where this seems to have worked before.  Look at
https://pyproveit.github.io/Prove-It//packages/proveit/logic/boolean/conjunction/_demonstrations_.html
In/Out [48]
That shows a groupCommute using length=3.  If you run that example again, does it do the right thing or is it broken?  If it does the right thing, what is different about this case and the examples you came up with where it wasn't working?

**Comment by wwitzel** [comment]
There are also groupCommute examples in the disjunction package:
https://pyproveit.github.io/Prove-It//packages/proveit/logic/boolean/disjunction/_demonstrations_.html
starting with In/Out [44].
Those examples look correct.

**Comment by wdcraft01** [comment]
Possibly a difference between starting and ending indices that look like this:

1, 0 (i.e. start > end)

versus

0, 1 (start < end)

and possibly interacting with disjunction versus conjunction? Still looking.
— H

________________________________

**Comment by wwitzel** [comment]
Hoss, in trying to reproduce your bug, I noticed it is correct when you use "groupCommute" and correct when you use "groupCommutation" moving from 0 to 1, but incorrect when you use "groupCommutation" moving from 1 to 0.  Strange.

**Comment by wwitzel** [comment]
I found the bug.  It's line 74 of generic_methods.py.  initIdx+length should be length.  Do you want to commit the fix, or do you want me to just commit this directly into master now?

**Comment by wdcraft01** [comment]
I found that one as well. Since you're there, you might as well do that, especially if you think that's the only issue.
Thanks! — H

________________________________

**Comment by wwitzel** [comment]
Okay.  Sorry for the delay.  I'll commit that fix soon.

**Comment by wwitzel** [comment]
Okay, I pushed the fix into master.  Hopefully I didn't break anything in the process.
