### ISSUE TITLE
Convert generators to ExprLists

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#9]
OperationOverInstances has some methods that yield (generate) Expression objects.  Modify the assignment behavior (magics.py) so it automatically converts the generator to an ExprList.  The current behavior could be confusing.

**Comment by wwitzel** [comment]
Instead of doing something fancy, we could have the output properly show that generators are assigned.  But then good practice should be to return expression lists rather than generators.  Either approach would work.

**Comment by wwitzel** [comment]
The simplest and probably most sensible solution is to return lists instead.  Private methods (preceded by underscore) can be implemented via generators, but the public methods should wrap the generator in a list to be returned.  Hoss started implementing this.

**Comment by wdcraft01** [comment]
I think we can close this small issue — see the recent pull request from
craft_edits_OperationOverInstances_GenToExprLists branch.

**Comment by wwitzel** [comment]
Fixed with merger of Craft_edits_OperationOverInstances_GensToExprLists.
