### ISSUE TITLE
Revise and finish proof that sqrt(2) is not rational

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#93]

**Comment by wdcraft01** [comment]
Reactivating this issue thread and establishing a new related branch (which will be branch 93).
In the short term, @bobcarr5 and I are working on structured proofs and related implementations for some of the supporting theorems used in the broader proof that sqrt(2) is not rational. A little bit of such work was begun spontaneously in branch 113, but I will try to simplify that branch a bit, rebase and squash, then pull it into branch 93.

**Comment by wwitzel** [comment]
Addressed via 93-sqrt2-proof and related branches.
