### ISSUE TITLE
Consider distinction between Set and MultiSet

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#96]
Our current Set class, in the logic/set_theory/enumeration context, allows the construction of an enumerated set, such as {a, b, c} with Set(a, b, c), but also allows a multi-set (or “bag”) construction, such as {a, b, c, a} with Set(a, b, c, a). Such multisets or bags can have a life all their own similar to but distinct from sets. Is it possible that we want the Set class to be restricted to allow non-multisets? Is it possible we want a separate class to represent multisets or bags?
Some related reading:
https://en.wikipedia.org/wiki/Multiset#Basic_properties_and_operations
http://www.cs.appstate.edu/~dap/classes/1100/sect2_2.html (see the section on “Bags”)

**Comment by wdcraft01** [comment]
Quick follow-up to elaborate briefly on how/why the set-vs.-multiset is causing me some concern. Suppose we use the Set class to create the enumerated multisets S1 and S2 defined by:
S1 = Set(a, a, b, b, c) = {a, a, b, b, c}
and
S2 = Set(a, b, b, c) = {a, b, b, c}.
The “support” for a multiset is the underlying “set” of the multiset (i.e. stripping out repeated elements). Thus S1 and S2 have the same underlying support {a, b, c} and in that sense Wayne argues that S1 and S2 are set-equivalent. Fair enough. We can then note that the set equivalence of S1 and S2 is axiomatically defined as:
(S1 &cong; S2) = (S1 &subseteq; S2) &and; (S2 &subseteq; S1),
which would then involve the somewhat suspicious-looking claim that
{a, a, b, b, c} &subseteq; {a, b, b, c},
where we allow the multiset notation but are enforcing the support-set interpretation of each side.
Related to this, in recently working on permutations and subsets of enumerated sets, I've ended up allowing claims such as
|– {a, a, b, b, c} &cong; {a, b, a, b, c}
that is, a multiset is set-equivalent to a permutation of itself, but I ended up <i>disallowing</i> something like this:
|– {a, a, b, b, c} &cong; {a, b, c}
because I was focused at the time on the multi-set aspect of the enumerated sets &mdash; they are not really permutations of one another, despite them being set-equivalent in the sense of them having the same fundamental support set. But of course I realize now this is inconsistent with the support-set interpretation of set-equivalence.
This leads to the question of whether or not we want to consider something like {a, b, c} to be a permutation of {a, a, b, c}.
Similarly, I had barreled ahead with enumerated subsets again thinking of a set such as {a, a, b, c} as a multiset and allowing proper subsets for something like
|– {a, a, b, c} &subset; {a, a, b, b, c}
but demanding the improper subset notation for this:
|– {a, a, b, c, b} &subseteq; {a, a, b, b, c}
Sticking with a strict set-equivalence notion based on the underlying support sets, both of those expressions would require the improper subset notation &subseteq;.
Should I redevelop this so that |– {a, a, b, c} &subset; {a, a, b, b, c} is in fact a False statement?

**Comment by wdcraft01** [comment]
It seems to me that one way to deal with some of these issues might be to restrict the Set class to  actual sets, disallowing multisets. This might be enacted implicitly, allowing the user to call something like Set(a, a, b, b, c) and producing (without error message) the set {a, b, c}, or by disallowing such multiset requests with an error message. A separate Multiset class might be then be useful, and some thought given to how Sets and Multisets might interact (or be such interaction be disallowed) when considering equivalence, subsets, etc.

**Comment by wwitzel** [comment]
The Set is not meant to be a multi-set.  {a, b, c, a} = {a, b, c}.

**Comment by wwitzel** [comment]
Closing this issue.  For now, implementing a multi-set is not planned.
