### ISSUE TITLE
Update QPE Content

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#97]
A major task consisting of updating/upgrading the physics/quantum/QPE and related materials
to current Prove-It system.
As I write this, I had already created a new branch for this work (QPE-beginning-20200116), but will now create a new branch from master with this Issue label, merge some preliminary changes into that from the QPE-beginning-20200116 branch, and continue from there.

**Comment by wdcraft01** [comment]
Re-establishing a dedicated branch for continued work on QPE: branch 97-Update-QPE-Content.

**Comment by wwitzel** [comment]
I'm currently working on fail_ineq proof.  Previously, I added Sum.deduce_bound and Add.decuce_bound methods, but this has been pulled into master already.  Now I'm starting to update Sum.factor and Div.factor.  Sum.factor lead me to dealing with value substitution of conditions (an "instance substitution" concept).  That touches Conditionals, Equals, and possibly OperationOverInstances -- still working out the interface on all of that.
